"""Shared Pydantic v2 contracts.

Every layer (API, agents, MCP servers, DB access) imports its schemas from here
so the structured I/O between agents stays consistent.
"""
from __future__ import annotations

from datetime import UTC, datetime
from uuid import UUID

from pydantic import BaseModel, Field


class ErrorLog(BaseModel):
    """Inbound production error report (FastAPI /ingest body)."""

    service: str
    message: str
    stacktrace: str = ""
    occurred_at: datetime
    metadata: dict = Field(default_factory=dict)


class HarnessSpec(BaseModel):
    """Generated by the Triage agent. Defines the exact environment needed to
    reproduce the crash."""

    file_path: str
    env_vars: dict[str, str] = Field(default_factory=dict)
    db_seed_sql: str | None = None
    mocked_services: list[str] = Field(default_factory=list)
    timeout_seconds: int = 120
    expected_exit_code: int = 0


class HarnessResult(BaseModel):
    """Emitted by the QA agent. Stored in TimescaleDB and fed back to the Dev
    agent on retry."""

    run_id: UUID
    passed: bool
    coverage_delta: float  # must be >= 0 to allow a PR
    failed_assertions: list[str] = Field(default_factory=list)
    duration_ms: int
    teardown_clean: bool = True
    retry_attempt: int = 0
    patch_diff: str | None = None
    pr_url: str | None = None
    recorded_at: datetime = Field(default_factory=lambda: datetime.now(UTC))


class TriageOutput(BaseModel):
    """Structured LLM output from the Triage node."""

    root_cause: str
    affected_file: str
    harness_spec: HarnessSpec


class PatchOutput(BaseModel):
    """Structured LLM output from the Dev node."""

    patch_diff: str  # unified diff
    conftest: str  # full conftest.py content
    explanation: str  # short summary for the PR body
