apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: prodrescue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: worker
          image: ${ECR_REGISTRY}/prodrescue:${IMAGE_TAG}
          command: ["celery", "-A", "services.api.tasks", "worker", "--loglevel=info", "--concurrency=2"]
          ports:
            - containerPort: 9100   # prometheus worker metrics
          envFrom:
            - secretRef:
                name: prodrescue-secrets
          env:
            - name: WORKER_METRICS_PORT
              value: "9100"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
